---
kind: pipeline
name: linux-amd64

platform: 
  os: linux
  arch: amd64

workspace:
  base: /go
  path: src/github.com/artificerpi/goserve

steps:
- name: test
  image: golang
  pull: always
  commands:
  - go test -v ./...
  
- name: build
  image: golang
  pull: always
  commands:
  - go get github.com/mitchellh/gox
  - go get -t -v ./...
  - gox -output="./dist/{{.Dir}}_{{.OS}}_{{.Arch}}" -os="linux darwin windows" -arch="amd64" -verbose ./...
  when:
    event:
    - push
    - tag

- name: publish
  image: plugins/github-release
  settings:
    api_key: [ github_token ]
    files: dist/*
    checksum:
      - sha256
  when:
    event: tag

...