---
kind: pipeline
name: linux-amd64

platform: 
  os: linux
  arch: amd64

steps:
- name: test
  image: golang
  pull: always
  commands:
  - go test -v ./...
  
- name: build
  image: golang
  pull: always
  commands:
  - go get github.com/mitchellh/gox
  - go get -t -v ./...
  - gox -os="linux darwin windows" -arch="amd64" -verbose ./...
  when:
    event:
    - push
    - tag

...