language: go
go:
- 1.x
- master
env:
  matrix:
  - PATH=/home/travis/gopath/bin:$PATH
before_install:
  - go get github.com/mitchellh/gox
script:
  - if [ "${LATEST}" = "true" ]; then gox -os="linux darwin windows" -arch="amd64" -output="logshare.." -ldflags "-X main.Rev=`git rev-parse --short HEAD`" -verbose ./...; fi
deploy:
  provider: releases
  api_key:
    secure: 051d32b6cae31341473af520b18715ddd9051a1d
  file:
    file:
    - goserve.windows.amd64.exe
    - goserve.darwin.amd64
    - goserve.linux.amd64
  skip_cleanup: true
  on:
    repo: artificerpi/goserve
    tags: true
