language: go
go:
- 1.x
- master
env:
  matrix:
  - PATH=/home/travis/gopath/bin:$PATH
before_install:
  - go get github.com/mitchellh/gox
script:
  - if [ "${LATEST}" = "true" ]; then gox -os="linux darwin windows" -arch="amd64" -output="logshare.." -ldflags "-X main.Rev=`git rev-parse --short HEAD`" -verbose ./...; fi
deploy:
  provider: releases
  api_key:
    secure: yyrPfbZACB3IAl1KHjcQxQo3mQyRU6eTBGGr1oQIINR6SHAUiFoULBJlZXOgKIVz8owNUs0idLJd9Vjp9TAUCUjbqnVSyyF8S2EvyzVh0CnpdFL4VNrD+1L0Vw7xxd6DOJXOmBqgK3wnXSG4jlwfOL5gXwActmpjVdD+6Hl1MrFHU4Cx+YyvBxHh7FMo3EkmbjZshPuWaqCntAsaJ9e7hi+B3IPqFHNxNpNbGvYImaVNHBVzXsBWwLDRC02tAmBRgTdIN7NCqLMG1jFOhtWopdO5nQ+k0MEE6fza36Jlg2W65jw12UWf7B8yD1jraNIAlwBwJzcfHa4poK6LKdvXEWn1uLnP3TXYTCeAaFZulMHQbUg9uQGcaBDuNSNEECjihcdRLNVZBItwIUgDWk4+rig1x/yoO4psHnJ6HeCqC5tayzCF5LUwh/rVoLzAJR0zI7tFC665ZmTeviU+mjcaDFEv75M6azA3TzrCMubW3cqZAxHLGptYG3HHgMCLyW82GE/nY3lre+7E12oM9OeHVzvMyM8Nm3+KDm00yckgtaV4YqMsq5DqvJ67CqiAMvtLSjSzViR0UZCDSqG2hazMahps8g90c87XhdjNiU3CAL+8xZKmii80JzhFBXrmUrXjHwRZRKUO9RKxDMmKrq5vFDgJ6hSsaND81PTi0WwVSN4=
  file:
    file:
    - goserve.windows.amd64.exe
    - goserve.darwin.amd64
    - goserve.linux.amd64
  skip_cleanup: true
  on:
    repo: artificerpi/goserve
    tags: true
