language: go
go:
- 1.x
- master
env:
  matrix:
  - PATH=/home/travis/gopath/bin:$PATH
before_install:
  - go get github.com/mitchellh/gox
script:
  - if [ "${LATEST}" = "true" ]; then gox -os="linux darwin windows" -arch="amd64" -output="logshare.." -ldflags "-X main.Rev=`git rev-parse --short HEAD`" -verbose ./...; fi
deploy:
  provider: releases
  api_key:
    secure: AAAAB3NzaC1yc2EAAAADAQABAAACAQDelLrZH3hfGkAhG22Yv4DD5bV04CTtKDxi8f70Ct6chgeZLNQvEZcocGXYyXql/JSQmjlHhHPMmtZbLwMInsLEazGglRVJ5nB78xLjdGMvOSPEQ5sXq0F3ZbZC/+gUVYU4Wm5uSI5oJA4nzUbLGHeuO1lWwsi2NbSL/JqwbSyuLxOf75WlC+Otqoi8ywOw8tHTftuoIUtaD2OM2s0mMSvyhoxy4buP6g2GFQEJ289kEQSt1kqDfuIzjwKGC1kcr3ujXZYtsqqDVQT8s9LkNXSUFcck+ocQTMrDNkZcR9Ds6NJ3m6ZOi9ll/v1AgBrcZrY3dmgPrLvDn7bvlkz8v5GdYlIUiSgEaOsLXEfD2Lp7ggc1/VcvwJ7qZXI5jxXWyPduFLUaRd4uz6pGF5IV7Jh3Ma3HjVNAv+7zvIzsHim1u7m2D7562EOR7ZxdkXFQZzY0ODsi4+1q7DsmZiLmA8lNeHy345qkp0vsdaEX9h5J7rHYlwy+8vC6q27h8OMezSi6/G4szHyPDSk339/lVjiVZS0nX07NSmN7OGfeMBSa2XIO8a93ueZNIkwOUzKG1a7ROMnfLiGUqy86oJSr4tOfqrUOVlDjeclQpF0JTF41B2vqOqmRGcNA97iKdmj+PysnjR+JPnelqDg1mpP+qxT99GO1FhFrDnejP2bg+1A1Dw==
  file:
    file:
    - goserve.windows.amd64.exe
    - goserve.darwin.amd64
    - goserve.linux.amd64
  skip_cleanup: true
  on:
    repo: artificerpi/goserve
    tags: true
    condition: $LATEST = true
