language: go
go:
- 1.x
- master
env:
  matrix:
  - PATH=/home/travis/gopath/bin:$PATH
before_install:
  - go get github.com/mitchellh/gox
script:
  - if [ "${LATEST}" = "true" ]; then gox -os="linux darwin windows" -arch="amd64" -output="logshare.." -ldflags "-X main.Rev=`git rev-parse --short HEAD`" -verbose ./...; fi
deploy:
  provider: releases
  api_key:
    secure: Cfem2iXY1T2zQXgcOSobpO/SCqLsqa0sFdofMAp4ViHVtkyXjkS1wtef964dpOs/F0zyG3zKgVegfTFjtp/iqHibOyXNL7Fmui3BreMMlWsWgqwzIViK1yo83zVRmY3bdMNkC1zULYN+M+bB8YSLt4ZEjDRfwzN8xgZcz5/ZXLizQDnA7fZO3uHLFd9PsdPsNHrI/UUB2hyXeNA6uLqko1oSzJeUGhTat3Gq3vOsHJrgpmdVKzvDDiB3/i/m7nE1G5NX+4rKqYv6MKPcj44II7zUJ/hUUMIo9Vg4K8o0+x9w8iRgNGsPpjVcS8D4q7NmHAyT/4cRboPm89q387WunKvupB5bXTKjwCIlTwmRXadS5taKmGx+K1oX2V/8Yx03Xz0W7j/E+WYDi0vaPwqAwVCuPd6gkAPtYJwYDVMtP40K6V4ZIzg97fD7U3G8zNtBvPBza+64RbRqx46bUSm14WusLNUA1Nz60FCp/xzr/Y/GfEKDwD5+juY8KnoT2VTOvor/khRuwrCfCFbHwMLppFW92AV1iPzDphYK4ABypTkIMnXDw+pJAjS44IMYGITz5BvMDhu/Smp17N3X8aPG8oXwQUlPcVWFih9RhGdd/MRm8UOrzY6tfydEMb2I9RRDHN5reURRn5YDR6UHUTxURV3SqWqdf9UL3JjWDHWew/4=
  file:
    file:
    - goserve.windows.amd64.exe
    - goserve.darwin.amd64
    - goserve.linux.amd64
  skip_cleanup: true
  on:
    repo: artificerpi/goserve
    tags: true
