language: go
go:
- 1.x
- master
env:
  matrix:
  - PATH=/home/travis/gopath/bin:$PATH
before_install:
  - go get github.com/mitchellh/gox
script:
  - if [ "${LATEST}" = "true" ]; then gox -os="linux darwin windows" -arch="amd64" -output="logshare.." -ldflags "-X main.Rev=`git rev-parse --short HEAD`" -verbose ./...; fi
deploy:
  provider: releases
  api_key:
    secure: erbPRGEez5MGSONzXWcvO76bOVtzFVFPm4vlONjuV7aNo07WroEzt7YPQ4b3AwmBBPG4FZ9U8EZQVdG9XTK01c+YTJnwdwy/b7ienQlLN0WOj2rrT8gy0xbGBPnDklNToTdscIkj2wySxXi85LUFtbNS0JukQWaIi/JAE6uYMImFKsYwnFyH+oaEzNg6ThDYgtuSO2JYY0ZktpaisanJ/PjQ2XgYHVREm7lg9EslySSBDX+VNziI4PTyT77kliAvpsIMvF2r/+Thv7+gEupOpX4g0MMbAaW9/HvgQLRImuj0IVd16BgtzjVpBdSlbCdZgt7pZM8k1ZNb/9XmoAojjRKik8R4U3ieKr4ek6s7PsPljeq6Iqj+fkYaOBbeOcGmeeXfVqiV11uiB7r1Ep8j4g8JdrlhUEE4h7dOv5e9rFB+Hem1FV6IMHp0SijylDrGowhP1Gnh1YEV+tSSHPuKiA3T4AQ2uiXdZmhZNYtDIW48BwwQKwcfKOUMtalEqBkungzpY2khXdF0L26wESlA1z519jQ2gM7D582KPvvfBRgiqoVRoEJ2a1cCELIm8/eR/iW0JNvlTRStK4kq397m3v08VX9PiM3ORQSI26iHj+7YdSw2WaQvZ6Iuqq+7WBy4YMuoXDQf/9v25fcdtE2QV2uCc3cz7NWUSqElnqaMby8=
  file:
    file:
    - goserve.windows.amd64.exe
    - goserve.darwin.amd64
    - goserve.linux.amd64
  skip_cleanup: true
  on:
    repo: artificerpi/goserve
    tags: true
